server:
  port: 8081
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/kinopoisk
    username: postgres
    password: 3gor
  liquibase:
    change-log: classpath:db/databasechangelog.xml
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  application:
    name: KinopoiskParser
  jpa:
    show-sql: true
api-key: YBYZT8C-893MX4Y-MNWKER5-A3MS8X5
